# Uncomment the next line to define a global platform for your project
 platform :ios, '12.1'

target 'weather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weather

pod 'Alamofire', '~> 4.8.2'
pod 'Moya', '~> 13.0'


end
